### ISSUE TITLE
Error Running docker-compose: cannot import name LogConfig

### ISSUE THREAD

**Issue by leonardoborlot** [akaunting/docker#25]
Hi guys

using your docker-compose I find this error:

server:~/akaunting# AKAUNTING_SETUP=true docker-compose up -d
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from ..bundle import get_image_digests
  File "/usr/lib/python2.7/dist-packages/compose/bundle.py", line 14, in <module>
    from .service import format_environment
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 13, in <module>
    from docker.utils import LogConfig
ImportError: cannot import name LogConfig

**Comment by MohammedAl-Mahdawi** [comment]
Hey @leonardoborlot,

I was not able to reproduce the issue, everything working fine on my end, I believe you have issues in your specific setup.
You can share your setup with me if you want however if your setup beyond our official compose setup then unfortunately I can't help you with it.
