### ISSUE TITLE
Can't get wizard, getting 500 on login

### ISSUE THREAD

**Issue by gempain** [akaunting/docker#29]
Hi ! I'm using the following `docker-compose.yml`, slightly adapted from the main example to not use env files (local setup for now os OSX):

```yaml
version: '3.7'

services:

  akaunting:
    image: docker.io/akaunting/akaunting:latest
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./data/akaunting/data:/var/www/html/storage
      - ./data/akaunting/modules:/var/www/html/modules
    restart: unless-stopped
    environment:
      APP_URL: "http://localhost:8080"
      LOCALE: "en-US"
      DB_HOST: "akaunting-db"
      DB_DATABASE: "akaunting"
      DB_USERNAME: "admin"
      DB_PASSWORD: "akaunting_password"
      DB_PREFIX: "asd_"
      COMPANY_NAME: "My Company"
      COMPANY_EMAIL: "my@company.com"
      ADMIN_EMAIL: "me@company.com"
      ADMIN_PASSWORD: "password"
    depends_on:
      - akaunting-db

  akaunting-db:
    image: mariadb
    volumes:
      - ./data/akaunting/db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: akaunting
      MYSQL_USER: admin
      MYSQL_PASSWORD: akaunting_password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
```

1. Run `AKAUNTING_SETUP=true docker-compose up -d`
2. When I get to localhost:8080, I see the login screen instead of - I'm assuming - the wizard
3. If I try to login, I get a 500:
![Screen Shot 2021-04-07 at 15 42 51](https://user-images.githubusercontent.com/13135149/113876346-f038dd80-97b7-11eb-8564-b719886cf7f5.png)

Here are the logs:

```
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using xxxx. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using xxxx. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 07 13:37:37.207318 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.16 configured -- resuming normal operations
[Wed Apr 07 13:37:37.207625 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.28.0.1 - - [07/Apr/2021:13:37:37 +0000] "GET / HTTP/1.1" 302 1561 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:37 +0000] "GET /auth/login HTTP/1.1" 200 3698 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/opensans/css/opensans.css?v=2.1.9 HTTP/1.1" 200 962 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/css/akaunting-color.css?v=2.1.9 HTTP/1.1" 200 6152 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/css/custom.css?v=2.1.9 HTTP/1.1" 200 7240 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/nucleo/css/nucleo.css?v=2.1.9 HTTP/1.1" 200 2336 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/fontawesome/css/all.min.css?v=2.1.9 HTTP/1.1" 200 12780 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/css/element.css?v=2.1.9 HTTP/1.1" 200 39657 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/css/argon.css?v=2.1.9 HTTP/1.1" 200 58344 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/jquery/dist/jquery.min.js HTTP/1.1" 200 30660 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/img/akaunting-logo-white.svg HTTP/1.1" 200 1069 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/js-cookie/js.cookie.js HTTP/1.1" 200 1834 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/livewire/livewire.js?id=d9e06c155e467adb5de2 HTTP/1.1" 200 39425 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/bootstrap/dist/js/bootstrap.bundle.min.js HTTP/1.1" 200 21046 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/js/auth/login.js?v=2.1.9 HTTP/1.1" 200 97584 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/img/login.png HTTP/1.1" 200 85766 "http://localhost:8080/public/css/custom.css?v=2.1.9" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/fontawesome/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 76409 "http://localhost:8080/public/vendor/fontawesome/css/all.min.css?v=2.1.9" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/opensans/fonts/OpenSans-Regular.ttf HTTP/1.1" 200 96715 "http://localhost:8080/public/vendor/opensans/css/opensans.css?v=2.1.9" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/opensans/fonts/OpenSans-SemiBold.ttf HTTP/1.1" 200 100544 "http://localhost:8080/public/vendor/opensans/css/opensans.css?v=2.1.9" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/bootstrap/dist/js/bootstrap.bundle.min.js.map HTTP/1.1" 200 77113 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/img/favicon.ico HTTP/1.1" 200 99981 "http://localhost:8080/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.28.0.1 - - [07/Apr/2021:13:37:38 +0000] "GET /public/vendor/livewire/livewire.js.map HTTP/1.1" 200 109316 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
127.0.0.1 - - [07/Apr/2021:13:37:46 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.16 (internal dummy connection)"
127.0.0.1 - - [07/Apr/2021:13:37:47 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.16 (internal dummy connection)"
[2021-04-07 13:37:52] production.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akaunting.asd_users' doesn't exist (SQL: select * from `asd_users` where `email` = me@company.com and `asd_users`.`deleted_at` is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akaunting.asd_users' doesn't exist (SQL: select * from `asd_users` where `email` = me@company.com and `asd_users`.`deleted_at` is null limit 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(638): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(346): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2313): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2301): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2796): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2302): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(588): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(572): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(242): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(131): Illuminate\\Database\\Eloquent\\Builder->first()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(358): Illuminate\\Auth\\EloquentUserProvider->retrieveByCredentials(Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(332): Illuminate\\Auth\\SessionGuard->attempt(Array, false)
#12 /var/www/html/app/Http/Controllers/Auth/Login.php(39): Illuminate\\Auth\\AuthManager->__call('attempt', Array)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Auth\\Login->store(Object(App\\Http\\Requests\\Auth\\Login))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\Login), 'store')
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/html/app/Http/Middleware/RedirectIfAuthenticated.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/html/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Firewall\\Abstracts\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/html/vendor/akaunting/laravel-language/src/Middleware/SetLocale.php(95): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Akaunting\\Language\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/html/app/Http/Middleware/LoadCurrencies.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\LoadCurrencies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/html/app/Http/Middleware/LoadSettings.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\LoadSettings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/html/app/Http/Middleware/AddXHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\AddXHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/www/html/app/Http/Middleware/RedirectIfNotInstalled.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectIfNotInstalled->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#75 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /var/www/html/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#93 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#94 /var/www/html/index.php(20): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#95 {main}
```

**Comment by Markoftw** [comment]
Same issue for me, using steps from the documentation.

**Comment by terindo** [comment]
please try to seed db :)

![image](https://user-images.githubusercontent.com/82742589/116015197-aaf32780-a662-11eb-8419-22e798fe6ed0.png)

**Comment by MohammedAl-Mahdawi** [comment]
Hi,

This repo is for building the official Akaunting images so please only post issues related to the official Akaunting images or the default setup of the compose files.

If you have questions or issues with your specific setup you can post your question/issue in our support channels [here](https://akaunting.com/support) or on StackOverflow.

Thank you for understanding!

**Comment by Chouaib99** [comment]
I have the same issue, Can someone help ?
