### ISSUE TITLE
production.ERROR: Target class [Dingo\Api\Routing\Router] does not exist.

### ISSUE THREAD

**Issue by Spessarite** [akaunting/docker#67]
Updating PHP to 8.1 causes the akaunting container to no longer work. Throws exceptions upon attempting to connect then goes to a white screen. Docker log with relevant error:
```
[2022-06-07 15:53:49] production.ERROR: Target class [Dingo\Api\Routing\Router] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [Dingo\\Api\\Routing\\Router] does not exist. at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:877)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\\Container\\Container->build('Dingo\\\\Api\\\\Routi...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\\Container\\Container->resolve('Dingo\\\\Api\\\\Routi...', Array, true)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('Dingo\\\\Api\\\\Routi...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\\Container\\Container->make('Dingo\\\\Api\\\\Routi...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('Dingo\\\\Api\\\\Routi...', Array)
#5 /var/www/html/modules/BC21/Routes/api.php(11): app('Dingo\\\\Api\\\\Routi...')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(152): require('/var/www/html/m...')
#7 /var/www/html/modules/BC21/Providers/Main.php(42): Illuminate\\Support\\ServiceProvider->loadRoutesFrom('/var/www/html/m...')
#8 /var/www/html/modules/BC21/Providers/Main.php(25): Modules\\BC21\\Providers\\Main->loadRoutes()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Modules\\BC21\\Providers\\Main->register()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Modules\\BC21\\Providers\\Main))
#11 /var/www/html/vendor/akaunting/laravel-module/src/Laravel/Module.php(27): Illuminate\\Foundation\\ProviderRepository->load(Array)
#12 /var/www/html/vendor/akaunting/laravel-module/src/Module.php(274): Akaunting\\Module\\Laravel\\Module->registerProviders()
#13 /var/www/html/vendor/akaunting/laravel-module/src/FileRepository.php(327): Akaunting\\Module\\Module->register()
#14 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Bootstrap.php(23): Akaunting\\Module\\FileRepository->register()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Akaunting\\Module\\Providers\\Bootstrap->register()
#16 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Main.php(29): Illuminate\\Foundation\\Application->register(Object(Akaunting\\Module\\Providers\\Bootstrap))
#17 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Laravel.php(17): Akaunting\\Module\\Providers\\Main->registerModules()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Akaunting\\Module\\Providers\\Laravel->boot()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(928): Illuminate\\Container\\Container->call(Array)
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(909): Illuminate\\Foundation\\Application->bootProvider(Object(Akaunting\\Module\\Providers\\Laravel))
#25 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Akaunting\\Module\\Providers\\Laravel), 24)
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): array_walk(Array, Object(Closure))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(239): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#32 /var/www/html/index.php(20): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#33 {main}

[previous exception] [object] (ReflectionException(code: -1): Class \"Dingo\\Api\\Routing\\Router\" does not exist at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:875)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(875): ReflectionClass->__construct('Dingo\\\\Api\\\\Routi...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\\Container\\Container->build('Dingo\\\\Api\\\\Routi...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\\Container\\Container->resolve('Dingo\\\\Api\\\\Routi...', Array, true)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('Dingo\\\\Api\\\\Routi...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\\Container\\Container->make('Dingo\\\\Api\\\\Routi...', Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('Dingo\\\\Api\\\\Routi...', Array)
#6 /var/www/html/modules/BC21/Routes/api.php(11): app('Dingo\\\\Api\\\\Routi...')
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(152): require('/var/www/html/m...')
#8 /var/www/html/modules/BC21/Providers/Main.php(42): Illuminate\\Support\\ServiceProvider->loadRoutesFrom('/var/www/html/m...')
#9 /var/www/html/modules/BC21/Providers/Main.php(25): Modules\\BC21\\Providers\\Main->loadRoutes()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Modules\\BC21\\Providers\\Main->register()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Modules\\BC21\\Providers\\Main))
#12 /var/www/html/vendor/akaunting/laravel-module/src/Laravel/Module.php(27): Illuminate\\Foundation\\ProviderRepository->load(Array)
#13 /var/www/html/vendor/akaunting/laravel-module/src/Module.php(274): Akaunting\\Module\\Laravel\\Module->registerProviders()
#14 /var/www/html/vendor/akaunting/laravel-module/src/FileRepository.php(327): Akaunting\\Module\\Module->register()
#15 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Bootstrap.php(23): Akaunting\\Module\\FileRepository->register()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Akaunting\\Module\\Providers\\Bootstrap->register()
#17 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Main.php(29): Illuminate\\Foundation\\Application->register(Object(Akaunting\\Module\\Providers\\Bootstrap))
#18 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Laravel.php(17): Akaunting\\Module\\Providers\\Main->registerModules()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Akaunting\\Module\\Providers\\Laravel->boot()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(928): Illuminate\\Container\\Container->call(Array)
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(909): Illuminate\\Foundation\\Application->bootProvider(Object(Akaunting\\Module\\Providers\\Laravel))
#26 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Akaunting\\Module\\Providers\\Laravel), 24)
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): array_walk(Array, Object(Closure))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(239): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#33 /var/www/html/index.php(20): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#34 {main}
"}
[2022-06-07 15:53:49] production.ERROR: Method Illuminate\Http\Request::isApi does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Http\\Request::isApi does not exist. at /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113)
[stacktrace]
#0 /var/www/html/app/Exceptions/Handler.php(63): Illuminate\\Http\\Request->__call('isApi', Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(427): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\\Foundation\\Http\\Kernel->renderException(Object(Illuminate\\Http\\Request), Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#3 /var/www/html/index.php(20): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#4 {main}
"}
[2022-06-07 15:53:49] production.ERROR: Uncaught BadMethodCallException: Method Illuminate\Http\Request::isApi does not exist. in /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
Stack trace:
#0 /var/www/html/app/Exceptions/Handler.php(63): Illuminate\Http\Request->__call('isApi', Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(220): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(BadMethodCallException))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(197): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(BadMethodCallException))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(BadMethodCallException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(BadMethodCallException))
#5 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught BadMethodCallException: Method Illuminate\\Http\\Request::isApi does not exist. in /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
Stack trace:
#0 /var/www/html/app/Exceptions/Handler.php(63): Illuminate\\Http\\Request->__call('isApi', Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(220): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(BadMethodCallException))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(197): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(BadMethodCallException))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(BadMethodCallException))
#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(Object(BadMethodCallException))
#5 {main}
  thrown at /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113)
[stacktrace]
#0 {main}
"}
```
And the log when I attempt to see php artisan view:clear inside the container:
```
[2022-06-07 16:30:52] production.ERROR: Target class [Dingo\Api\Routing\Router] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [Dingo\\Api\\Routing\\Router] does not exist. at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:877)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\\Container\\Container->build('Dingo\\\\Api\\\\Routi...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\\Container\\Container->resolve('Dingo\\\\Api\\\\Routi...', Array, true)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('Dingo\\\\Api\\\\Routi...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\\Container\\Container->make('Dingo\\\\Api\\\\Routi...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('Dingo\\\\Api\\\\Routi...', Array)
#5 /var/www/html/modules/BC21/Routes/api.php(11): app('Dingo\\\\Api\\\\Routi...')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(152): require('/var/www/html/m...')
#7 /var/www/html/modules/BC21/Providers/Main.php(42): Illuminate\\Support\\ServiceProvider->loadRoutesFrom('/var/www/html/m...')
#8 /var/www/html/modules/BC21/Providers/Main.php(25): Modules\\BC21\\Providers\\Main->loadRoutes()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Modules\\BC21\\Providers\\Main->register()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Modules\\BC21\\Providers\\Main))
#11 /var/www/html/vendor/akaunting/laravel-module/src/Laravel/Module.php(27): Illuminate\\Foundation\\ProviderRepository->load(Array)
#12 /var/www/html/vendor/akaunting/laravel-module/src/Module.php(274): Akaunting\\Module\\Laravel\\Module->registerProviders()
#13 /var/www/html/vendor/akaunting/laravel-module/src/FileRepository.php(327): Akaunting\\Module\\Module->register()
#14 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Bootstrap.php(23): Akaunting\\Module\\FileRepository->register()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Akaunting\\Module\\Providers\\Bootstrap->register()
#16 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Main.php(29): Illuminate\\Foundation\\Application->register(Object(Akaunting\\Module\\Providers\\Bootstrap))
#17 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Laravel.php(17): Akaunting\\Module\\Providers\\Main->registerModules()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Akaunting\\Module\\Providers\\Laravel->boot()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(928): Illuminate\\Container\\Container->call(Array)
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(909): Illuminate\\Foundation\\Application->bootProvider(Object(Akaunting\\Module\\Providers\\Laravel))
#25 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Akaunting\\Module\\Providers\\Laravel), 24)
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): array_walk(Array, Object(Closure))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(239): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#31 /var/www/html/artisan(22): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 {main}

[previous exception] [object] (ReflectionException(code: -1): Class \"Dingo\\Api\\Routing\\Router\" does not exist at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:875)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(875): ReflectionClass->__construct('Dingo\\\\Api\\\\Routi...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\\Container\\Container->build('Dingo\\\\Api\\\\Routi...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\\Container\\Container->resolve('Dingo\\\\Api\\\\Routi...', Array, true)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('Dingo\\\\Api\\\\Routi...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\\Container\\Container->make('Dingo\\\\Api\\\\Routi...', Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('Dingo\\\\Api\\\\Routi...', Array)
#6 /var/www/html/modules/BC21/Routes/api.php(11): app('Dingo\\\\Api\\\\Routi...')
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(152): require('/var/www/html/m...')
#8 /var/www/html/modules/BC21/Providers/Main.php(42): Illuminate\\Support\\ServiceProvider->loadRoutesFrom('/var/www/html/m...')
#9 /var/www/html/modules/BC21/Providers/Main.php(25): Modules\\BC21\\Providers\\Main->loadRoutes()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Modules\\BC21\\Providers\\Main->register()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Modules\\BC21\\Providers\\Main))
#12 /var/www/html/vendor/akaunting/laravel-module/src/Laravel/Module.php(27): Illuminate\\Foundation\\ProviderRepository->load(Array)
#13 /var/www/html/vendor/akaunting/laravel-module/src/Module.php(274): Akaunting\\Module\\Laravel\\Module->registerProviders()
#14 /var/www/html/vendor/akaunting/laravel-module/src/FileRepository.php(327): Akaunting\\Module\\Module->register()
#15 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Bootstrap.php(23): Akaunting\\Module\\FileRepository->register()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Akaunting\\Module\\Providers\\Bootstrap->register()
#17 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Main.php(29): Illuminate\\Foundation\\Application->register(Object(Akaunting\\Module\\Providers\\Bootstrap))
#18 /var/www/html/vendor/akaunting/laravel-module/src/Providers/Laravel.php(17): Akaunting\\Module\\Providers\\Main->registerModules()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Akaunting\\Module\\Providers\\Laravel->boot()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(928): Illuminate\\Container\\Container->call(Array)
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(909): Illuminate\\Foundation\\Application->bootProvider(Object(Akaunting\\Module\\Providers\\Laravel))
#26 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Akaunting\\Module\\Providers\\Laravel), 24)
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): array_walk(Array, Object(Closure))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(239): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#32 /var/www/html/artisan(22): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 {main}
"}

In Container.php line 877:

  Target class [Dingo\Api\Routing\Router] does not exist.


In Container.php line 875:

  Class "Dingo\Api\Routing\Router" does not exist

```

**Comment by gortium** [comment]
I get the same issue. @Spessarite, have you find a fix?

**Comment by Spessarite** [comment]
It was an issue with outdated apps, see [here](https://akaunting.com/forum/discussion/installation-update/updating-to-300-failed-cant-manually-update-either)
